### ISSUE TITLE
Random crashes on screen rotation

### ISSUE THREAD

**Issue by ykrapiva** [rusfearuth/zxing-lib-extended#1]
Play with a rotation for a while and you'll get the following:

11-12 23:11:55.200: ERROR/AndroidRuntime(5889): FATAL EXCEPTION: Thread-370
        java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
        at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:48)
        at com.google.zxing.client.android.camera.CameraManager.buildLuminanceSource(CameraManager.java:339)
        at zxing.library.DecodeHandler.decode(DecodeHandler.java:77)
        at zxing.library.DecodeHandler.handleMessage(DecodeHandler.java:59)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at zxing.library.DecodeThread.run(DecodeThread.java:97)

I assume if (rotation == Surface.ROTATION_0) and the image data buildLuminanceSource(byte[] data...) get out of sync

**Comment by rusfearuth** [comment]
I'll try to fix that

**Comment by mutkan** [comment]
I also get this exception.

java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
       at com.abhi.barcode.fragment.barcode.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:46)
       at com.google.zxing.client.android.camera.CameraManager.buildLuminanceSource(CameraManager.java:321)
       at com.abhi.barcode.fragment.barcode.DecodeHandler.decode(DecodeHandler.java:77)
       at com.abhi.barcode.fragment.barcode.DecodeHandler.handleMessage(DecodeHandler.java:57)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:150)
       at com.abhi.barcode.fragment.barcode.DecodeThread.run(DecodeThread.java:81)

**Comment by woutergoossens** [comment]
Any possible fix?

**Comment by rusfearuth** [comment]
Today, I have some pass time for work around this problem

**Comment by rusfearuth** [comment]
@woutergoossens Could you test this crash? I couldn't repeat bug after updated zxing core to 3.1.
